window.team = [
  {
    name: "Олег Мозіль",
    age: "30",
    number: "1",
    position: "Воротар",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_384.png?1758399278",
    photo2: "https://metalist1925.com/players/gallery/players384/img_239.jpg",
    goals: "",
    assists: "",
    matches: "",
  },
  {
    name: "Ярослав Проценко",
    age: "24",
    number: "24",
    position: "Воротар",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_482.png?1758864961",
    photo2: "https://metalist1925.com/players/gallery/players482/img_281.jpg",
    goals: "",
    assists: "",
    matches: "1",
  },
  {
    name: "Данило Варакута",
    age: "24",
    number: "30",
    position: "Воротар",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_534.png?1776738438",
    photo2: "https://metalist1925.com/sys/files/news/original/folder2/post_7082.webp?1730742677",
    goals: "",
    assists: "",
    matches: "30",
  },
  {
    name: "Дмитро Капінус",
    age: "22",
    number: "2",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_381.png?1762228033",
    photo2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYi1LKS8Y2rMWKdHIkTh2gDrJmDqvYdYa4LA&s",
    goals: "",
    assists: "",
    matches: "8",
  },
  {
    name: "Володимир Салюк",
    age: "23",
    number: "13",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_522.png?1776738478",
    photo2: "https://pic.sport.ua/images/news/0/21/97/orig_859594.jpg",
    goals: "",
    assists: "3",
    matches: "16",
  },
  {
    name: "Євген Павлюк",
    age: "23",
    number: "18",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_576.png?1776738509",
    photo2: "https://metalist1925.com/sys/files/news/original/folder7/post_8137.webp?1773495014",
    goals: "2",
    assists: "2",
    matches: "29",
  },
  {
    name: "Олександр Мартинюк",
    age: "24",
    number: "24",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_572.png?1776738592",
    photo2: "https://metalist1925.com/sys/files/news/original/folder8/post_8288.webp?1777651208",
    goals: "",
    assists: "",
    matches: "19",
  },
  {
    name: "Ілля Крупський",
    age: "21",
    number: "27",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_556.png?1776738649",
    photo2: "https://metalist1925.com/sys/files/news/original/folder6/post_7766.webp?1759236607",
    goals: "",
    assists: "4",
    matches: "30",
  },
  {
    name: "Артем Шабанов",
    age: "34",
    number: "31",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_579.png?1776311695",
    photo2: "https://upl.ua/glide/uploads/2508/k2pP7kS4U00o3tZtQT_SZuHGdona9JkK.jpg?w=900&h=540&fit=contain&s=1ccb4df6db09dc09a27197a280640cd5",
    goals: "1",
    assists: "1",
    matches: "28",
  },
  {
    name: "Валерій Дубко",
    age: "25",
    number: "37",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_646.png?1776738544",
    photo2: "https://metalist1925.com/sys/files/news/original/folder6/post_8126.webp?1773131722",
    goals: "",
    assists: "",
    matches: "4",
  },
  {
    name: "Ігор Снурніцин",
    age: "26",
    number: "74",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_531.png?1761878151",
    photo2: "https://fc-metalist.com/news/img/6933.jpg",
    goals: "",
    assists: "",
    matches: "2",
  },
  {
    name: "Іван Калюжний",
    age: "28",
    number: "5",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_241.png?1776738726",
    photo2: "https://xsport.ua/_next/image/?url=https%3A%2F%2Fems.xsport.ua%2Fsites%2Fdefault%2Ffiles%2F2025-09%2F%25D0%259A%25D0%25B0%25D0%25BB%25D1%258E%25D0%25B6%25D0%25BD%25D0%25B8%25D0%25B9%2520130925.jpg&w=1920&q=70",
    goals: "3",
    assists: "3",
    matches: "28",
  },
  {
    name: "Арі Моура",
    age: "29",
    number: "7",
    position: "Півзахисник",
    nationality: "Бразілія",
    photo: "https://metalist1925.com/players/foto/img_423.png?1776738751",
    photo2: "https://en.metalist1925.com/players/gallery/players423/img_183.jpg",
    goals: "",
    assists: "1",
    matches: "15",
  },
  {
    name: "Себастіан Кастільо",
    age: "21",
    number: "8",
    position: "Півзахисник",
    nationality: "Венесуела",
    photo: "https://metalist1925.com/players/foto/img_642.png?1775761558",
    photo2: "https://metalist1925.com/sys/files/foto/27/img_59927.jpg",
    goals: "",
    assists: "",
    matches: "7",
  },
  {
    name: "В'ячеслав Чурко",
    age: "32",
    number: "11",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_512.png?1773711168",
    photo2: "https://metalist1925.com/sys/files/news/original/folder2/post_7962.webp?1765573479",
    goals: "1",
    assists: "1",
    matches: "17",
  },
  {
    name: "Рамік Гаджиєв",
    age: "20",
    number: "14",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_546.png?1775655147",
    photo2: "https://dynamo.kiev.ua/media/posts/2025/09/25/111_dynamo.kiev.ua_111_3.jpg",
    goals: "2",
    assists: "",
    matches: "5",
  },
  {
    name: "Денис Антюх",
    age: "28",
    number: "15",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_578.png?1776738926",
    photo2: "https://metalist1925.com/sys/files/foto/16/img_59916.jpg",
    goals: "5",
    assists: "4",
    matches: "28",
  },
  {
    name: "Ніколас Аревало",
    age: "23",
    number: "16",
    position: "Півзахисник",
    nationality: "Колумбія",
    photo: "https://metalist1925.com/players/foto/img_643.png?1776738901",
    photo2: "https://metalist1925.com/sys/files/foto/08/img_59908.jpg",
    goals: "",
    assists: "1",
    matches: "10",
  },
  {
    name: "Ігор Когут",
    age: "30",
    number: "17",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_520.png?1776738820",
    photo2: "https://metalist1925.com/sys/files/news/original/folder4/post_8214.webp?1775818140",
    goals: "",
    assists: "4",
    matches: "22",
  },
  {
    name: "Ермір Рашиця",
    age: "22",
    number: "19",
    position: "Півзахисник",
    nationality: "Албанія",
    photo: "https://metalist1925.com/players/foto/img_564.png?1776738948",
    photo2: "https://pictures.ua.tribuna.com/image/bfe622a0-515c-4417-89af-6246e76756b8?width=1920&quality=70",
    goals: "3",
    assists: "2",
    matches: "28",
  },
  {
    name: "Іван Литвиненко",
    age: "25",
    number: "25",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_529.png?1776738878",
    photo2: "https://pic.sport.ua/images/news/0/21/81/orig_856341.jpg",
    goals: "3",
    assists: "1",
    matches: "23",
  },
  {
    name: "Владислав Калітвінцев",
    age: "33",
    number: "45",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_513.png?1776311978",
    photo2: "https://static.ua-football.com/img/upload/22/2d014e.jpeg",
    goals: "1",
    assists: "3",
    matches: "24",
  },
  {
    name: "Кауан Баптістелла",
    age: "18",
    number: "77",
    position: "Півзахисник",
    nationality: "Бразилія",
    photo: "https://metalist1925.com/players/foto/img_648.png?1776738848",
    photo2: "https://pictures.ua.tribuna.com/image/9996654a-7173-4493-9deb-cb5468a5016f?width=1920&quality=70",
    goals: "1",
    assists: "",
    matches: "8",
  },
  {
    name: "Андрій Король",
    age: "17",
    number: "88",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_438.png?1776438498",
    photo2: "https://metalist1925.com/sys/files/news/original/folder0/post_7590.webp?1754407373",
    goals: "",
    assists: "",
    matches: "1",
  },
  {
    name: "Матвій Панченко",
    age: "20",
    number: "91",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_411.png?1776438595",
    photo2: "https://metalist1925.com/sys/files/news/original/folder2/post_6262.webp?1703756206",
    goals: "",
    assists: "2",
    matches: "5",
  },
  {
    name: "Батон Забергджа",
    age: "25",
    number: "26",
    position: "Нападник",
    nationality: "Косово",
    photo: "https://metalist1925.com/players/foto/img_614.png?1776312055",
    photo2: "https://metalist1925.com/sys/files/news/original/folder6/post_8226.webp?1776179845",
    goals: "3",
    assists: "1",
    matches: "22",
  },
  {
    name: "Пітер Ітодо",
    age: "22",
    number: "98",
    position: "Нападник",
    nationality: "Нігерія",
    photo: "https://metalist1925.com/players/foto/img_580.png?1776738970",
    photo2: "https://sport-express.ua/img/news/UPL/Metalist1925/itodo209209.webp",
    goals: "13",
    assists: "1",
    matches: "27",
  },
  {
    name: "Крістіан Мба",
    age: "26",
    number: "99",
    position: "Нападник",
    nationality: "Нігерія",
    photo: "https://metalist1925.com/players/foto/img_557.png?1776738793",
    photo2: "https://metalist1925.com/sys/files/foto/50/img_59350.jpg",
    goals: "5",
    assists: "",
    matches: "23",
  },
];
window.coaches = [
  {
    name: "Младен Бартулович",
    age: "39",
    position: "Тренерскій штаб",
    coach: "Головний тренер",
    nationality: "Хорватія",
    photo: "https://metalist1925.com/players/foto/img_577.png?1755117221",
  },
  {
    name: "Олександр Чижов",
    age: "39",
    position: "Тренерскій штаб",
    coach: "Помічник головного тренера",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_538.png?1755116118",
  },
  {
    name: "Сергій Долганський",
    age: "51",
    position: "Тренерскій штаб",
    coach: "Тренер воротарів",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_581.png?1755116423",
  },
  {
    name: "Максим Цвіренко",
    age: "27",
    position: "Тренерскій штаб",
    coach: "Асистент тренера",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_161.png?1755116556",
  },
  {
    name: "Євген Шахов",
    age: "35",
    position: "Тренерскій штаб",
    coach: "Асистент тренера",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_590.png?1751656279",
  },
  {
    name: "Валентин Єрмак",
    age: "25",
    position: "Тренерскій штаб",
    coach: "Тренер-аналітик",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_613.png?1755118044",
  },
  {
    name: "Павло Таран",
    age: "37",
    position: "Тренерскій штаб",
    coach: "Тренер-аналітик",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_640.png?1768079073",
  },
  {
    name: "Андрій Шабалін",
    age: "38",
    position: "Тренерскій штаб",
    coach: "Тренер з фізподготовки",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_311.png?1755115676",
  },
  {
    name: "Драган Тодорович",
    age: "38",
    position: "Тренерскій штаб",
    coach: "Тренер з фізподготовки",
    nationality: "Хорватія",
    photo: "https://metalist1925.com/players/foto/img_589.png?1755115968",
  },
];

window.managment = [
{
   name: "Богдан Бойко",
   role: "Президент",
   age: "27",
   nationality: "Україна",
   photo: "https://ukrfootball.ua/wp-content/uploads/UPL/Metalist1925/boiko9456.webp",
},
{
   name: "Володимир Носов",
   role: "Голова наглядової ради",
   age: "36",
   nationality: "Україна",
   photo: "https://ukrfootball.ua/wp-content/uploads/UPL/Metalist1925/njsov0.webp",
},
{
   name: "Юрій Коротун",
   role: "Віцепрезидент",
   age: "41",
   nationality: "Україна",
   photo: "https://metalist1925.com/players/foto/img_535.png?1755110054",
},
{
   name: "Антон Іванов",
   role: "Генеральний директор",
   age: "42",
   nationality: "Україна",
   photo: "https://metalist1925.com/players/foto/img_273.png?1734494771",
},
];
  window.matches = [
{
  date: "09.05.26",
  opponent: "Зоря Луганьск",
  time: "18:00",
  place: "Стадіон імені Лобановського, Київ",
  competition: "УПЛ",
},
{
  date: "13.05.26",
  opponent: "Карпати Львів",
  time: "",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
},
{
  date: "16.05.26",
  opponent: "Епіцентр Кам'янець-Подільський",
  time: "",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
},
{
  date: "23.05.26",
  opponent: "Верес Рівне",
  time: "",
  place: "Стадіон Авангард, Рівне",
  competition: "УПЛ",
},
];
window.results = [
{
  date: "03.05.26",
  opponent: "Полісся Житомир",
  score: "0-1",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
},
  {
  date: "26.04.26",
  opponent: "ЛНЗ Черкаси",
  place: "Центральний стадіон, Черкаси",
  competition: "УПЛ",
  score: "1-1",
},
  {
  date: "22.04.26",
  opponent: "ФК Чернигів",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "Кубок України",
  score: "0-0 (5:6 по пенальті)",
},
  {
  date: "18.4.26",
  opponent: "Кудрівка",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "1-0",
},
{
  date: "15.4.26",
  opponent: "Верес Рівне",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "4-0",
},  
{
  date: "11.4.26",
  opponent: "Динамо Київ",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "1-0",
},
{
  date: "4.4.26",
  opponent: "Колос Ковалівка",
  place: "Колос, Ковалівка",
  competition: "УПЛ",
  score: "0-0",
},
{
  date: "19.3.26",
  opponent: "ФК Полтава",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "2-0",
},
{
  date: "15.3.26",
  opponent: "Шахтар Донецьк",
  place: "Арена Львів, Львів",
  competition: "УПЛ",
  score: "1-0",
},
{
  date: "9.3.26",
  opponent: "Рух Львів",
  place: "Арена Львів, Львів",
  competition: "УПЛ",
  score: "0-3",
},
{
  date: "5.3.26",
  opponent: "Локомотив Київ",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "Кубок України",
  score: "3-0",
},
{
  date: "28.2.26",
  opponent: "Олександрія",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "1-0",
},
{
  date: "21.2.26",
  opponent: "Кривбас Кривий Ріг",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "0-0",
},
{
  date: "12.12.25",
  opponent: "Оболонь Київ",
  place: "Оболонь Арена, Київ",
  competition: "УПЛ",
  score: "1-3",
},
{
  date: "30.11.25",
  opponent: "Епіцентр Кам'янець-Подільський",
  place: "Міський стадіон, Тернопіль",
  competition: "УПЛ",
  score: "0-0",
},
{
  date: "22.11.25",
  opponent: "Карпати Львів",
  place: "Стадіон Україна, Львів",
  competition: "УПЛ",
  score: "1-2",
},

{
  date: "8.11.25",
  opponent: "Зоря Луганьск",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "1-3",
},

{
  date: "3.11.25",
  opponent: "Полісся Житомир",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "0-0",
},
{
  date: "30.10.25",
  opponent: "Агробізнес Волочиськ",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "Кубок України",
  score: "4-3",
},
{
  date: "25.10.25",
  opponent: "ЛНЗ Черкаси",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "0-1",
},
{
  date: "28.9.25",
  opponent: "Кудрівка",
  place: "Оболонь Арена, Київ",
  competition: "УПЛ",
  score: "1-1",
},
{
  date: "5.10.25",
  opponent: "Динамо Київ",
  place: "Стадіон імені Лобановського, Київ",
  competition: "УПЛ",
  score: "1-1",
},
{
  date: "28.9.25",
  opponent: "Колос Ковалівка",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "1-0",
},
{
  date: "24.9.25",
  opponent: "Колос Полонне",
  place: "Полонь, Полонне",
  competition: "Кубок України",
  score: "1-4",
},
{
  date: "21.9.25",
  opponent: "ФК Полтава",
  place: "Стадіон Зірка.Кропивницький",
  competition: "УПЛ",
  score: "0-2",
},
{
  date: "13.9.25",
  opponent: "Шахтар Донецьк",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "1-1",
},
{
  date: "30.8.25",
  opponent: "Рух Львів",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "2-0",
},
{
  date: "24.8.25",
  opponent: "Оболонь Київ",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "Кубок України",
  score: "2-0",
},
{
  date: "16.8.25",
  opponent: "Олександрія",
  place: "КСК Ніка, Олександрія",
  competition: "УПЛ",
  score: "1-4",
},

{
  date: "9.8.25",
  opponent: "Кривбас Кривий Ріг",
  place: "Стадіон Гірник, Кривий Ріг",
  competition: "УПЛ",
  score: "2-0",
},
{
  date: "4.8.25",
  opponent: "Оболонь Київ",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "0-0",
},
];
